### ISSUE TITLE
about instance-level image segmentation

### ISSUE THREAD

**Issue by lufeiyang598** [GewelsJI/SINet-V2#10]
Hello, I have noticed that there are already instance-level image annotations in COD10K. Can SINet support instance-level segmentation now? If not, I want to try to improve it to the instance level. Please provide your suggestions. Thank you.

**Comment by GewelsJI** [comment]
Hello, @lufeiyang598 

Nice question here. I think this [repo](https://github.com/PJLallen/OSFormer) would help you a lot.

Best,
Ge-Peng.

**Comment by lufeiyang598** [comment]
I didn't expect SINet to already have V3, which was really helpful for me, thank you.

**Comment by GewelsJI** [comment]
Yes. Please enjoy it.
