### ISSUE TITLE
What is the difference between RF and TEM?

### ISSUE THREAD

**Issue by lunaWU628** [GewelsJI/SINet-V2#11]
It's a great job！

**Question1：** What is the difference between RF and TEM? In my opinion, RF and TEM are the same。

SINetv1
![image](https://user-images.githubusercontent.com/90367095/221464213-72a015d5-4f5d-420b-9315-a7612bf33cac.png)
SINetv2
![image](https://user-images.githubusercontent.com/90367095/221464296-28334ee9-5d7e-4352-94c1-8d03af0ee36e.png)

**Question2：** I want to use the TEM module, which part of the network structure works best? (Is it OK to put the TEM module behind the backbone?) ）

This may be a simple question, but it is important to me, hope to get a response from you, thank you!

**Comment by GewelsJI** [comment]
Hi, @lunaWU628 

Thank you for raising such a good question here.

A1: As described in original paper, we just use RF-like module to extract texture cues. I refer you to the first part of section 4.2:  "This motivates us to use the TEM [63] to incorporate more discriminative feature representations during the searching stage (usually in a small/local space)."

A2: I really suggest you use RF-like module to extract multi-scale information from backbone's features. It usually improves the model performance.

I hope these answers help you a lot.

Best,
Ge-Peng.

**Comment by lunaWU628** [comment]
Thank you very much for your quick answer, this is very helpful to me.

Best wishes for you!
