### ISSUE TITLE
About the presentation of camouflaged object detection

### ISSUE THREAD

**Issue by lunaWU628** [GewelsJI/SINet-V2#13]
Hello, read a lot of your articles, I feel that you have a deep knowledge in camouflage biological detection, I want you a question: most of the current camouflage object detection is based on saliency detection as a method, and finally presented in a way like "**segmentation**", do you think that the detection of camouflage organisms in the form of **bounding boxes** can be?

**Comment by GewelsJI** [comment]
Hi, @lunaWU628 

A good question here. You are right, current salient object detection methods actually solve the perception problem in a segmentation way. The detection is a degradation task of segmentation, and thus, this way sounds reasonable somewhat cause you can easily convert the segmentation label to bounding box (ie, coordinates). Detecting camouflaged object in a detection way is also good direction, but I strongly suggest you can explore some interesting methods using per-pixel segmentation strategies.

I hope this answer can address your concerns above.

Best,
Ge-Peng.

**Comment by lunaWU628** [comment]
Thank you for your positive response. Have a nice day!
