### ISSUE TITLE
指标计算代码

### ISSUE THREAD

**Issue by whyandbecause** [GewelsJI/SINet-V2#14]
您好，我在使用计算指标的代码时，经常出现多个函数找不到的问题，如 _未定义与 'double' 类型的输入参数相对应的函数 'bwdist'。_ 想请教下是matlab版本问题还是其他原因？谢谢！

**Comment by GewelsJI** [comment]
我猜测是你没有安装对应的计算包（https://www.mathworks.com/help/images/ref/bwdist.html），可以考虑查询一下相关问题是否有解决方案

**Comment by whyandbecause** [comment]
感谢，已解决，是少了Image Processing Toolbox这个工具包。但是计算指标的速度有点慢，CAMO一个测试集的计算都需要10来分钟，这是正常的吗？

**Comment by GewelsJI** [comment]
可以开启parallel计算模式（parfor）
