### ISSUE TITLE
请问COD10K中bounding box的标注在哪，只看到了object annotation，即GT

### ISSUE THREAD

**Issue by K-tang-mkv** [GewelsJI/SINet-V2#16]

**Comment by GewelsJI** [comment]
Hi, @K-tang-mkv 

Please go to this link: https://dengpingfan.github.io/pages/COD.html, and find the dataset download link: https://drive.google.com/file/d/1vRYAie0JcNStcSwagmCq55eirGyMYGm5/view

Best.
