### ISSUE TITLE
gt = randomPeper(gt) - Data augmentation of the ground truth?

### ISSUE THREAD

**Issue by AlexanderAleksander** [GewelsJI/SINet-V2#18]
Dear Authors,

thanks for sharing the code.

Please let me know, if this line is correct
gt = randomPeper(gt)

should this not be applied to the image instead?

Thanks

Alexander

**Comment by GewelsJI** [comment]
Confirm it's correct. Just to introduce some randomness on ground-truth, and also to avoid the all-zero conditions.
