### ISSUE TITLE
Error about E-measure.

### ISSUE THREAD

**Issue by jokerhcy** [GewelsJI/SINet-V2#2]
Dear author, I would like to ask, in the process of paper re-emergence, according to the statement of the article (except for batch size replacement for 20) trained model of other indicators and the paper is very close, except E-measure difference is relatively large, is this in the acceptable range?
SINet_V2_Results：
 CHAMELEON (  76 images): S: 0.894, **E: 0.934**, F: 0.825, M: 0.030
 CAMO ( 250 images): S: 0.817, **E: 0.870**, F: 0.737, M: 0.072
 COD10K (2026 images): S: 0.813, **E: 0.864**, F: 0.676, M: 0.036

**Comment by GewelsJI** [comment]
E-measure has three types under different thresholding strategies, i.e., max, mean, and adapt. Which one did you adopt in the re-emergence?

**Comment by chiyuan-IVIPLab** [comment]
The adapt one. So the paper uses the mean or max one？

**Comment by GewelsJI** [comment]
We use the mean value of E-measure in our paper.

**Comment by chiyuan-IVIPLab** [comment]
Thank you so much, I would try again.

**Comment by GewelsJI** [comment]
Thank you for your attention to our paper. I will temporarily close this issue and you can open it anytime if you have further questions.
