### ISSUE TITLE
关于TEM模块的细节

### ISSUE THREAD

**Issue by Frank-Cai0709** [GewelsJI/SINet-V2#20]
作者您好，我看论文里的TEM模块图，对多个支路拼接后，使用了1*1conv。但是在代码中，对多支路concat后，conv_cat使用了3\*3Conv，请问是以代码为准么？
![image](https://github.com/GewelsJI/SINet-V2/assets/93969813/9b76706b-ee76-41a7-be8b-72fa58f7be2f)

![image](https://github.com/GewelsJI/SINet-V2/assets/93969813/ac159ea0-9fae-47b6-bcd6-26d9e88d668f)
![image](https://github.com/GewelsJI/SINet-V2/assets/93969813/79edc304-748f-4675-b905-892c37982443)

**Comment by GewelsJI** [comment]
您好，

感谢指正，这里以代码为主！

之前尝试对比过conv1*1和conv3*3，我印象中差异并不大，这里仅仅起到一个特征融合的作用，当然您也可以自行尝试一下具体差异。

祝好，
Daniel

**Comment by Frank-Cai0709** [comment]
好的，非常感谢您的回复～



---- 回复的原邮件 ----
| 发件人 | Daniel ***@***.***> |
| 日期 | 2024年05月07日 10:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [GewelsJI/SINet-V2] 关于TEM模块的细节 (Issue #20) |

您好，

感谢指正，这里以代码为主！

之前尝试对比过conv11和conv33，我印象中差异并不大，这里仅仅起到一个特征融合的作用，当然您也可以自行尝试一下具体差异。

祝好，
Daniel
