### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by clelouch** [GewelsJI/SINet-V2#3]
![image](https://user-images.githubusercontent.com/33519394/143669055-19c2e91b-6883-4aa6-b6df-b20c60bc5236.png)
Thanks for your sharing. I find that in your Mytrain_val.py, a validation dataset is utilized. I am not sure whether you use the CAMO for validation since the default `val_root` is `'./Dataset/TestDataset/CAMO/'` . Besides, the training/validation dataset link only contains the training set. Could you please tell me the training details?

**Comment by GewelsJI** [comment]
Yes. You can just use `./Dataset/TestDataset/CAMO/` during the validation period.

**Comment by clelouch** [comment]
Thank you.
