### ISSUE TITLE
Training and Testing Image Number 

### ISSUE THREAD

**Issue by ming1993li** [GewelsJI/SINet-V2#4]
Hi, authors, thank you very much for your great work. I downloaded the training/validation and testing data from your provided Google drive links. But I find the numbers do not match the figures in your PAMI paper. The number of training/validation images is 4040 rather than 6000+1250 in your paper. The number of testing images for COD10K is 2026 rather than 4000 in your paper. What is the problem? Could you please help to solve it? Thank you so much!

**Comment by DengPingFan** [comment]
Hi, 
Actually, for a fair comparison with our previous version (SINet-V1), we adopt the same training settings [1] for the baselines. 
In Table1, 6000 training images are the total number in our COD10K. However, we didn't use the non-camouflaged images as the training set.  In addition, the test image is also 2026 in our experiments. The 4000 image is only statistics of our COD10K. 

You can follow our code to train your model. 

Best,

**Comment by ming1993li** [comment]
Thank you for your prompt reply. So, in a word, the provided 4040 training/validation images and 2026 testing images are actually used by your PAMI paper, right? And I can employ the same setting to prepare for my own paper.

**Comment by DengPingFan** [comment]
Yes

Ming ***@***.***>于2021年12月22日 周三12:30写道：

**Comment by ming1993li** [comment]
Great, thank you so much!
